# Copyright (c) 2022-2024 Ali Hassani.
# This dockerfile builds on top of the March 2024 NGC PyTorch
# image, and builds NATTEN for SM60-SM90 with 16 workers.

FROM nvcr.io/nvidia/pytorch:24.03-py3

RUN mkdir /natten

RUN cd /natten && \
      git clone https://github.com/SHI-Labs/NATTEN

# NOTE: set WITH_CUDA=1 to prevent
# setuptools from looking for the cuda runtime.
RUN cd /natten/NATTEN && \
      make \
      WITH_CUDA=1 \
      CUDA_ARCH="6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0" \
      WORKERS=16
